apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceNames.frontend }}
  labels:
    app: waschplan
spec:
  selector:
    app: waschplan
    tier: frontend
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: {{.Values.nodePorts.frontend }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: waschplan-frontend-deployment
  labels:
    app: waschplan
    tier: frontend
spec:
  selector:
    matchLabels:
      app: waschplan
      tier: frontend
  template:
    metadata:
      labels:
        app: waschplan
        tier: frontend
    spec:
      containers:
        - name: waschplan-frontend-container
          image: {{ .Values.images.frontend}}
          ports:
            - containerPort: 80
          livenessProbe:
            tcpSocket:
              port: 80
          readinessProbe:
            tcpSocket:
              port: 80

